site_name: "re-frame"
site_description: Derived data, flowing
site_author: Mike Thompson
site_url: https://day8.github.io/re-frame/

repo_name: day8/re-frame
repo_url: https://github.com/day8/re-frame

copyright: Copyright &copy; 2015-2021 Michael Thompson

theme:
  name: material
  custom_dir: docs/theme
  icon: 
    logo: material/home
    repo: fontawesome/brands/git-alt
  language: en
  palette:
    primary: blue
    accent: blue
  font:
    text: IBM Plex Sans
    code: Source Code Pro
  features:
    - tabs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/day8
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wazound

nav:
  - Home: index.md
  - Docs:
    - "re-frame": re-frame.md
    - THE BASICS:
      - A Data Loop: a-loop.md
      - State: application-state.md
      - Code: dominoes-30k.md
      - Infographics: event-handling-infographic.md
      - Subscriptions: subscriptions.md
      - Live: dominoes-live.md
    - "INTERMEDIATE 2 & 3":
      - Effectful Handlers: EffectfulHandlers.md
      - Interceptors.md
      - Effects.md
      - Coeffects.md
      - Review TodoMVC: review-todomvc.md
    - "INTERMEDIATE 4,5 & 6":
      - Correcting a wrong: correcting-a-wrong.md
      - Flow Mechanics: flow-mechanics.md
    - "START CODING": start-coding.md
    - "MENTAL MODEL OMNIBUS":
      - "Other Models": all-models-are-wrong.md 
      - "On Dynamics":  on-dynamics.md
      - "Data Oriented Design": data-oriented-design.md
      - "Interconnections": interconnections.md
      - "Historical": historical.md
    - MORE ADVANCED:
      - Stable Dom Handlers: on-stable-dom-handlers.md
      - Browser Dynamics: browser-dynamics.md
      - Reusable Components: reusable-components.md
      - App Structure: App-Structure.md
      - Loading Initial Data: Loading-Initial-Data.md
      - Talking To Servers: Talking-To-Servers.md
      - Subscribing to External Data: Subscribing-To-External-Data.md
      - Debugging.md
      - Testing.md
      - Eek! Performance Problems: Performance-Problems.md
      - Solve the CPU hog problem: Solve-the-CPU-hog-problem.md
      - Using Stateful JS Components: Using-Stateful-JS-Components.md
      - The Logo Backstory: The-re-frame-logo.md
  - FAQs:
    - "How can I Inspect app-db?": FAQs/Inspecting-app-db.md
    - "How Do I Load On Mount?": FAQs/LoadOnMount.md
    - "Reagent looks terrific. Why do I need re-frame?": FAQs/DoINeedReFrame.md
    - "How to focus on an HTML element": FAQs/FocusOnElement.md
    - "How do I register a global interceptor": FAQs/GlobalInterceptors.md
    - "Why is my input field laggy?": FAQs/laggy-input.md
    - "How long after I do a dispatch does the event get handled?": FAQs/When-Does-Dispatch-Happen.md
    - "How can I use a subscription in an Event Handler": FAQs/UseASubscriptionInAnEventHandler.md
    - "How do I use logging method X": FAQs/Logging.md
    - "Dispatched Events Are Null": FAQs/Null-Dispatched-Events.md
    - "Why do we need to clear the subscription cache when reloading with Figwheel?": FAQs/Why-Clear-Sub-Cache.md
    - "How can I detect exceptions in Event Handlers?": FAQs/CatchingEventExceptions.md
    - "How do I turn on/off polling a database every 60 secs": FAQs/PollADatabaseEvery60.md
    - "re-frame uses side-effecting registrations. Should I feel dirty?": FAQs/ViewsOnGlobalRegistration.md
    - "Why is re-frame implemented in `.cljc` files": FAQs/Why-CLJC.md
    - "How do I store normalised data in app-db?": FAQs/DB_Normalisation.md    
    - "How do I do full-stack re-frame?": FAQs/FullStackReframe.md
  - API:
    - Overview: api-intro.md
    - Builtin Effects: api-builtin-effects.md
    - re-frame.core: api-re-frame.core.md
  - Releases:
    - 2021: releases/2021.md
    - 2020: releases/2020.md
    - 2019: releases/2019.md
    - 2018: releases/2018.md
    - 2017: releases/2017.md
    - 2016: releases/2016.md
    - 2015: releases/2015.md
  - Resources:
    - Resources: External-Resources.md

markdown_extensions:
  - meta
  - admonition
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 3
  - codehilite:
      guess_lang: false

extra_css:
  - "https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,300;0,500;1,400&display=swap"
  - "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200;300;400&display=swap"
  - "stylesheets/dominoes-live.css"
  - "stylesheets/codehilite-monokai.css"
  - "stylesheets/mkdocs.css"
